// build.rs — parse C sub-structs via bindgen to generate compile-time layout asserts.
// C header (structs.h) is the source of truth. Rust sub-structs must match.
//
// Verified types: device_hid_t, device_config_t, device_fw_t, device_led_t
// Excluded: device_hw_t (contains SDK-dependent opaque types, not bindgen-able)

use std::env;
use std::path::PathBuf;

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let project_root = manifest.parent().unwrap();
    let c_include = project_root.join("src/include");
    let header = c_include.join("structs.h");

    let bindings = bindgen::Builder::default()
        .header(header.to_str().unwrap())
        .clang_arg(format!("-I{}", c_include.display()))
        .clang_arg("--target=arm-none-eabi")
        .use_core()
        .layout_tests(true)
        .allowlist_type("device_hid_t")
        .allowlist_type("device_config_t")
        .allowlist_type("device_fw_t")
        .allowlist_type("device_led_t")
        .generate()
        .expect("bindgen failed — is structs.h SDK-free?");

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let code = bindings.to_string();
    let mut asserts = String::from(
        "// Auto-generated by build.rs (bindgen) — do not edit.\n\
         // Source of truth: src/include/structs.h\n\n"
    );

    // Bindgen 0.71 layout test format uses array-size trick (may span multiple lines).
    // Join all lines and parse assertions from the flattened text.
    let joined = code.replace('\n', " ");

    // For each sub-struct, extract size and field offsets
    for (c_type, rust_type) in [
        ("device_hid_t", "DeviceHid"),
        ("device_config_t", "DeviceConfig"),
        ("device_fw_t", "DeviceFw"),
        ("device_led_t", "DeviceLed"),
    ] {
        // Size assertion
        let size_pattern = format!("[\"Size of {c_type}\"]");
        if let Some(start) = joined.find(&size_pattern) {
            let rest = &joined[start..];
            if let Some(semi) = rest.find(';') {
                if let Some(val) = extract_value(&rest[..semi]) {
                    asserts.push_str(&format!(
                        "const _: () = assert!(core::mem::size_of::<{rust_type}>() == {val}, \
                         \"{rust_type} size mismatch with C {c_type}\");\n"
                    ));
                }
            }
        }

        // Alignment assertion
        let align_pattern = format!("[\"Alignment of {c_type}\"]");
        if let Some(start) = joined.find(&align_pattern) {
            let rest = &joined[start..];
            if let Some(semi) = rest.find(';') {
                if let Some(val) = extract_value(&rest[..semi]) {
                    asserts.push_str(&format!(
                        "const _: () = assert!(core::mem::align_of::<{rust_type}>() == {val}, \
                         \"{rust_type} alignment mismatch with C {c_type}\");\n"
                    ));
                }
            }
        }

        // Field offset assertions
        let field_pattern = format!("[\"Offset of field: {c_type}::");
        let mut search_from = 0;
        while let Some(pos) = joined[search_from..].find(&field_pattern) {
            let abs_pos = search_from + pos + field_pattern.len();
            let rest = &joined[abs_pos..];
            if let Some(field_end) = rest.find("\"]") {
                let c_field = &rest[..field_end];
                let assertion_rest = &rest[field_end..];
                if let Some(semi) = assertion_rest.find(';') {
                    let chunk = &assertion_rest[..semi];
                    // Map C field name to Rust field name
                    let rust_field = c_to_rust_field(c_field);
                    if let Some(val) = extract_value(chunk) {
                        asserts.push_str(&format!(
                            "const _: () = assert!(core::mem::offset_of!({rust_type}, {rust_field}) == {val}, \
                             \"{rust_type}::{rust_field} offset mismatch with C\");\n"
                        ));
                    }
                }
            }
            search_from = abs_pos;
        }
    }

    // Guard: fail build if parser produced nothing
    assert!(
        asserts.contains("const _:"),
        "build.rs: no layout assertions extracted from bindgen output — parser broken?"
    );

    std::fs::write(out_dir.join("device_offsets.rs"), &asserts)
        .expect("failed to write device_offsets.rs");

    println!("cargo:rerun-if-changed={}", header.display());
    for dep in ["flash.h", "packet.h", "screen.h", "constants.h", "api_config.h"] {
        println!("cargo:rerun-if-changed={}", c_include.join(dep).display());
    }
}

/// Extract numeric value from bindgen array-size trick: `[... - VALUEusize];`
fn extract_value(line: &str) -> Option<usize> {
    let marker = "- ";
    let suffix = "usize]";
    let end = line.rfind(suffix)?;
    let before = &line[..end];
    let start = before.rfind(marker)? + marker.len();
    before[start..].trim().parse().ok()
}

/// Map C field names to Rust field names (identity for most fields).
fn c_to_rust_field(c_field: &str) -> &str {
    match c_field {
        "_running_fw" => "running_fw",
        _ => c_field,
    }
}
