// build.rs — parse C structs.h via bindgen to generate compile-time layout asserts.
// C header is the source of truth. Rust Device struct must match.

use std::env;
use std::path::PathBuf;

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let project_root = manifest.parent().unwrap();
    let c_include = project_root.join("src/include");
    let header = c_include.join("structs.h");

    let bindings = bindgen::Builder::default()
        .header(header.to_str().unwrap())
        .clang_arg(format!("-I{}", c_include.display()))
        .clang_arg("--target=arm-none-eabi")
        .use_core()
        .layout_tests(true)
        .allowlist_type("device_t")
        .generate()
        .expect("bindgen failed — is structs.h SDK-free?");

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let code = bindings.to_string();
    let mut asserts = String::from(
        "// Auto-generated by build.rs (bindgen) — do not edit.\n\
         // Source of truth: src/include/structs.h\n\n"
    );

    // Bindgen 0.71 layout test format (array-size trick, may span two lines):
    //   ["Offset of field: device_t::config"][...offset_of!(...) - 88usize];
    //   OR:
    //   ["Offset of field: device_t::active_output"]
    //           [...offset_of!(...) - 32usize];
    //
    // Strategy: join all lines, then split on `["` boundaries.
    let joined = code.replace('\n', " ");

    // Size of device_t
    if let Some(start) = joined.find("[\"Size of device_t\"]") {
        let rest = &joined[start..];
        if let Some(val) = extract_value(rest) {
            asserts.push_str(&format!(
                "const _: () = assert!(core::mem::size_of::<Device>() == {val}, \
                 \"Device size mismatch with C\");\n"
            ));
        }
    }

    // Field offsets: find all ["Offset of field: device_t::FIELD"] patterns
    let pattern = "[\"Offset of field: device_t::";
    let mut search_from = 0;
    while let Some(pos) = joined[search_from..].find(pattern) {
        let abs_pos = search_from + pos + pattern.len();
        let rest = &joined[abs_pos..];
        if let Some(field_end) = rest.find("\"]") {
            let c_field = &rest[..field_end];
            // Find the value in the same assertion (up to the next semicolon)
            let assertion_rest = &rest[field_end..];
            if let Some(semi) = assertion_rest.find(';') {
                let chunk = &assertion_rest[..semi];
                if let Some(rust_field) = c_to_rust_field(c_field) {
                    if let Some(val) = extract_value(chunk) {
                        asserts.push_str(&format!(
                            "const _: () = assert!(core::mem::offset_of!(Device, {rust_field}) == {val}, \
                             \"{rust_field} offset mismatch with C\");\n"
                        ));
                    }
                }
            }
        }
        search_from = abs_pos;
    }

    // Guard: fail build if parser produced nothing (bindgen format may have changed)
    assert!(
        asserts.contains("const _:"),
        "build.rs: no layout assertions extracted from bindgen output — parser broken?"
    );

    std::fs::write(out_dir.join("device_offsets.rs"), &asserts)
        .expect("failed to write device_offsets.rs");

    println!("cargo:rerun-if-changed={}", header.display());
    for dep in ["flash.h", "packet.h", "screen.h", "constants.h", "api_config.h"] {
        println!("cargo:rerun-if-changed={}", c_include.join(dep).display());
    }
}

/// Extract numeric value from bindgen array-size trick: `[... - VALUEusize];`
fn extract_value(line: &str) -> Option<usize> {
    let marker = "- ";
    let suffix = "usize]";
    let end = line.rfind(suffix)?;
    let before = &line[..end];
    let start = before.rfind(marker)? + marker.len();
    before[start..].trim().parse().ok()
}

fn c_to_rust_field(c_field: &str) -> Option<&'static str> {
    match c_field {
        "tud_connected" => Some("usb_connected"),
        "active_output" => Some("active_output"),
        "core1_last_loop_pass" => Some("core1_last_loop_pass"),
        "reboot_requested" => Some("reboot_requested"),
        "blinks_left" => Some("blinks_left"),
        "config" => Some("config"),
        "iface" => Some("iface"),
        "page_buffer" => Some("page_buffer"),
        "keyboard_leds" => Some("keyboard_leds"),
        "pointer_x" => Some("pointer_x"),
        "_running_fw" => Some("running_fw"),
        "fw" => Some("fw"),
        "config_mode_timer" => Some("config_mode_timer"),
        _ => None,
    }
}
