// build.rs — parse C structs.h via bindgen to generate compile-time layout asserts.
// C header is the source of truth. Rust Device struct must match.

use std::env;
use std::path::PathBuf;

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let project_root = manifest.parent().unwrap();
    let c_include = project_root.join("src/include");

    // structs.h is now SDK-free — bindgen can parse it directly
    let header = c_include.join("structs.h");

    let bindings = bindgen::Builder::default()
        .header(header.to_str().unwrap())
        .clang_arg(format!("-I{}", c_include.display()))
        .clang_arg("--target=arm-none-eabi")
        .use_core()
        .layout_tests(true)
        .allowlist_type("device_t")
        .generate()
        .expect("bindgen failed — is structs.h SDK-free?");

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    // Write raw bindings for reference
    bindings.write_to_file(out_dir.join("bindings.rs"))
        .expect("failed to write bindings.rs");

    // Extract offset/size values from layout tests and generate const asserts
    let code = bindings.to_string();
    let mut asserts = String::from(
        "// Auto-generated by build.rs (bindgen) — do not edit.\n\
         // Source of truth: src/include/structs.h\n\n"
    );

    // Parse sizeof from: assert_eq!(::core::mem::size_of::<device_t>(), SIZE, ...)
    for line in code.lines() {
        if line.contains("size_of::<device_t>()") {
            if let Some(val) = extract_second_arg(line) {
                asserts.push_str(&format!(
                    "const _: () = assert!(core::mem::size_of::<Device>() == {val}, \
                     \"Device size mismatch with C\");\n"
                ));
            }
        }
        // Parse field offsets from: assert_eq!(... .field as *const _ as usize }, OFFSET, ...)
        if line.contains("as *const _ as usize }") {
            if let (Some(field), Some(offset)) = (extract_field(line), extract_second_arg(line)) {
                if let Some(rust_field) = c_to_rust_field(&field) {
                    asserts.push_str(&format!(
                        "const _: () = assert!(core::mem::offset_of!(Device, {rust_field}) == {offset}, \
                         \"{rust_field} offset mismatch with C\");\n"
                    ));
                }
            }
        }
    }

    std::fs::write(out_dir.join("device_offsets.rs"), &asserts)
        .expect("failed to write device_offsets.rs");

    println!("cargo:rerun-if-changed={}", header.display());
    for dep in ["flash.h", "packet.h", "screen.h", "constants.h"] {
        println!("cargo:rerun-if-changed={}", c_include.join(dep).display());
    }
}

fn extract_field(line: &str) -> Option<String> {
    // Pattern: )).field_name as *const
    let start = line.find(")).")?;
    let rest = &line[start + 3..];
    let end = rest.find(" as ")?;
    Some(rest[..end].to_string())
}

fn extract_second_arg(line: &str) -> Option<usize> {
    // Pattern: ...first_expr , VALUE , "msg")
    // Find the content between first and second comma after assert_eq!(
    let after_eq = line.find("assert_eq!(")?;
    let rest = &line[after_eq + 11..];
    let first_comma = rest.find(',')?;
    let after_first = rest[first_comma + 1..].trim_start();
    let second_comma = after_first.find(',')?;
    after_first[..second_comma].trim().parse().ok()
}

fn c_to_rust_field(c_field: &str) -> Option<&'static str> {
    match c_field {
        "tud_connected" => Some("usb_connected"),
        "active_output" => Some("active_output"),
        "core1_last_loop_pass" => Some("core1_last_loop_pass"),
        "reboot_requested" => Some("reboot_requested"),
        "blinks_left" => Some("blinks_left"),
        "config" => Some("config"),
        "iface" => Some("iface"),
        "page_buffer" => Some("page_buffer"),
        "keyboard_leds" => Some("keyboard_leds"),
        "pointer_x" => Some("pointer_x"),
        _ => None,
    }
}
