// Core data structures — bindgen-generated from C headers (structs.h, screen.h, flash.h).
// Types are re-exported with Rust naming conventions via `pub use ... as`.
// Hand-crafted types (HidInterface, etc.) remain for SDK-dependent structures
// that bindgen cannot parse.

use crate::domain::constants::{NUM_SCREENS, PACKET_DATA_LENGTH, RAW_PACKET_LENGTH};
use crate::domain::hid_parser::ReportVal;

// From hid_parser.h
pub const MAX_DEVICES: usize = 4;
pub const MAX_INTERFACES: usize = 4;
pub const MAX_REPORTS: usize = 24;
pub const MAX_KEYBOARDS: usize = 5;
pub const MAX_CC_BUTTONS: usize = 16;
pub const MAX_SYS_BUTTONS: usize = 8;
pub const MAX_KEYS: usize = 32;
pub const KEYS_IN_USB_REPORT: usize = 6;
pub const KBD_REPORT_LENGTH: usize = 8;

// From flash.h — Pico SDK FLASH_PAGE_SIZE = 256
pub const FLASH_PAGE_SIZE: usize = 256;

/* ================================================================== *
 * Bindgen-generated types from C headers.
 * Source of truth: src/include/structs.h, screen.h, flash.h
 * Generated by build.rs → bindgen_types.rs
 * ================================================================== */

#[allow(non_camel_case_types, non_snake_case, dead_code, clippy::all)]
mod bindgen {
    include!(concat!(env!("OUT_DIR"), "/bindgen_types.rs"));
}

// Re-export with Rust naming conventions
pub use bindgen::border_size_t as BorderSize;
pub use bindgen::screensaver_t as Screensaver;
pub use bindgen::output_t as Output;
pub use bindgen::firmware_metadata_t as FirmwareMetadata;
pub use bindgen::hid_kbd_report_t as HidKeyboardReport;
pub use bindgen::fw_upgrade_state_t as FwUpgradeState;
pub use bindgen::config_t as Config;
pub use bindgen::device_hid_t as DeviceHid;
pub use bindgen::device_config_t as DeviceConfig;
pub use bindgen::device_fw_t as DeviceFw;
pub use bindgen::device_led_t as DeviceLed;

/* ================================================================== *
 * Packet / HID report types (not in bindgen — depend on Rust constants
 * or SDK-dependent types that bindgen cannot parse)
 * ================================================================== */

#[derive(Debug, Clone, Copy, Default)]
#[repr(C, packed)]
pub struct UartPacketC {
    pub ptype: u8,
    pub data: [u8; PACKET_DATA_LENGTH],
    pub checksum: u8,
}

#[derive(Debug, Clone, Copy, Default)]
#[repr(C)]
pub struct MouseReportC {
    pub buttons: u8,
    pub x: i16,
    pub y: i16,
    pub wheel: i8,
    pub pan: i8,
    pub mode: u8,
}

#[derive(Debug, Clone, Copy, Default)]
#[repr(C)]
pub struct HidGenericPkt {
    pub instance: u8,
    pub report_id: u8,
    pub ptype: u8,
    pub len: u8,
    pub data: [u8; RAW_PACKET_LENGTH],
}

/* ================================================================== *
 * HID parser types (SDK-dependent — hand-crafted, not bindgen-able)
 * ================================================================== */

#[derive(Clone, Copy, Default)]
#[repr(C)]
pub struct MouseDescriptor {
    pub buttons: ReportVal,
    pub move_x: ReportVal,
    pub move_y: ReportVal,
    pub wheel: ReportVal,
    pub pan: ReportVal,
    pub report_id: u8,
    pub is_found: bool,
    pub uses_report_id: bool,
}

#[derive(Clone, Copy, Default)]
#[repr(C)]
pub struct KeyboardDescriptor {
    pub modifier: ReportVal,
    pub nkro: ReportVal,
    pub cc_array: [u16; MAX_CC_BUTTONS],
    pub sys_array: [u16; MAX_SYS_BUTTONS],
    pub key_array: [bool; MAX_KEYS],
    pub report_id: u8,
    pub key_array_idx: u8,
    pub uses_report_id: bool,
    pub is_found: bool,
    pub is_nkro: bool,
}

#[derive(Clone, Copy, Default)]
#[repr(C)]
pub struct ReportDescriptor {
    pub val: ReportVal,
    pub report_id: u8,
    pub is_variable: bool,
    pub is_array: bool,
}

/// Function pointer type for report handlers (C callback)
pub type ProcessReportFn = Option<unsafe extern "C" fn(*mut u8, i32, u8, *mut HidInterface)>;

#[derive(Clone, Copy)]
#[repr(C)]
pub struct HidInterface {
    pub keyboards: [KeyboardDescriptor; MAX_KEYBOARDS],
    pub num_keyboards: u8,
    pub mouse: MouseDescriptor,
    pub consumer: ReportDescriptor,
    pub system: ReportDescriptor,
    pub report_handler: [ProcessReportFn; MAX_REPORTS],
    pub protocol: u8,
    pub uses_report_id: bool,
}

/* ================================================================== *
 * Pico SDK queue_t — opaque, size varies by SDK version.
 * ================================================================== */

const QUEUE_T_SIZE: usize = 16;

#[derive(Clone, Copy)]
#[repr(C, align(4))]
pub struct QueueOpaque {
    _data: [u8; QUEUE_T_SIZE],
}

/* ================================================================== *
 * DeviceState — unified mutable view over sub-struct globals
 * ================================================================== */

extern "C" {
    pub static mut global_hid: DeviceHid;
    pub static mut global_cfg: DeviceConfig;
    pub static mut global_fw: DeviceFw;
    pub static mut global_led: DeviceLed;
}

/// Unified mutable view into all device sub-structs.
/// Created from extern globals at FFI entry points.
pub struct DeviceState<'a> {
    pub hid: &'a mut DeviceHid,
    pub cfg: &'a mut DeviceConfig,
    pub fw: &'a mut DeviceFw,
    pub led: &'a mut DeviceLed,
}

impl<'a> DeviceState<'a> {
    /// Create a DeviceState from the C extern globals.
    ///
    /// # Safety
    /// Must not be called concurrently on the same core (creates aliased &mut).
    /// Each core's task scheduler is single-threaded, so this is safe in practice.
    pub unsafe fn from_globals() -> Self {
        Self {
            hid: &mut *core::ptr::addr_of_mut!(global_hid),
            cfg: &mut *core::ptr::addr_of_mut!(global_cfg),
            fw: &mut *core::ptr::addr_of_mut!(global_fw),
            led: &mut *core::ptr::addr_of_mut!(global_led),
        }
    }

    pub fn is_active_output(&self) -> bool {
        self.cfg.active_output == self.cfg.board_role
    }

    /// Create zeroed sub-structs for testing.
    #[cfg(test)]
    pub fn zeroed_for_test() -> (DeviceHid, DeviceConfig, DeviceFw, DeviceLed) {
        unsafe {
            (
                core::mem::zeroed(),
                core::mem::zeroed(),
                core::mem::zeroed(),
                core::mem::zeroed(),
            )
        }
    }
}

/* ================================================================== *
 * Helper functions
 * ================================================================== */

/// Cast a C hid_interface_t* pointer to a Rust HidInterface reference.
/// SAFETY: caller must ensure ptr is valid and layout matches.
pub unsafe fn iface_from_ptr<'a>(iface: *mut core::ffi::c_void) -> &'a mut HidInterface {
    &mut *(iface as *mut HidInterface)
}

/// Look up keyboard descriptor by report_id (mirrors C get_keyboard).
pub fn get_keyboard(iface: &HidInterface, rid: u8) -> &KeyboardDescriptor {
    if iface.num_keyboards == 1 || !iface.uses_report_id {
        return &iface.keyboards[0];
    }
    for n in 0..iface.num_keyboards as usize {
        if n < MAX_KEYBOARDS && iface.keyboards[n].report_id == rid {
            return &iface.keyboards[n];
        }
    }
    &iface.keyboards[0]
}

/* ================================================================== *
 * Tests
 * ================================================================== */

#[cfg(test)]
mod tests {
    use super::*;
    use core::mem;

    #[test]
    fn test_uart_packet_size() {
        assert_eq!(mem::size_of::<UartPacketC>(), 10);
    }

    #[test]
    fn test_hid_keyboard_report_size() {
        assert_eq!(mem::size_of::<HidKeyboardReport>(), 8);
    }

    #[test]
    fn test_border_size() {
        assert_eq!(mem::size_of::<BorderSize>(), 8);
    }

    #[test]
    fn test_firmware_metadata_size() {
        let size = mem::size_of::<FirmwareMetadata>();
        assert!(size >= 10);
    }

    #[test]
    fn test_intermediate_struct_sizes() {
        use crate::domain::hid_parser::ReportVal;

        assert_eq!(mem::size_of::<ReportVal>(), 23, "ReportVal");
        assert_eq!(mem::size_of::<MouseDescriptor>(), 118, "MouseDescriptor");
        assert_eq!(mem::size_of::<KeyboardDescriptor>(), 132, "KeyboardDescriptor");
        assert_eq!(mem::size_of::<ReportDescriptor>(), 26, "ReportDescriptor");

        let ptr_size = mem::size_of::<usize>();
        let fn_ptr_size = mem::size_of::<ProcessReportFn>();
        assert_eq!(fn_ptr_size, ptr_size, "ProcessReportFn should be pointer-sized");
        if ptr_size == 4 {
            assert_eq!(mem::size_of::<HidInterface>(), 932, "HidInterface on 32-bit");
        }
    }

    #[test]
    fn test_config_struct_sizes() {
        assert_eq!(mem::size_of::<Screensaver>(), 24, "Screensaver");
        assert_eq!(mem::size_of::<FwUpgradeState>(), 12, "FwUpgradeState");
        assert_eq!(mem::size_of::<FirmwareMetadata>(), 12, "FirmwareMetadata");
        assert_eq!(mem::size_of::<QueueOpaque>(), 16, "QueueOpaque");
    }

    #[test]
    fn test_report_val_field_offsets() {
        use crate::domain::hid_parser::ReportVal;
        assert_eq!(mem::offset_of!(ReportVal, offset), 0);
        assert_eq!(mem::offset_of!(ReportVal, offset_idx), 2);
        assert_eq!(mem::offset_of!(ReportVal, size), 4);
        assert_eq!(mem::offset_of!(ReportVal, usage_min), 6);
        assert_eq!(mem::offset_of!(ReportVal, usage_max), 10);
        assert_eq!(mem::offset_of!(ReportVal, item_type), 14);
        assert_eq!(mem::offset_of!(ReportVal, data_type), 15);
        assert_eq!(mem::offset_of!(ReportVal, report_id), 16);
        assert_eq!(mem::offset_of!(ReportVal, global_usage), 17);
        assert_eq!(mem::offset_of!(ReportVal, usage_page), 19);
        assert_eq!(mem::offset_of!(ReportVal, usage), 21);
    }
}
